import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderSelector from "@/layout/RootLayout/Header/HeaderSelector";
import FooterSelector from "@/layout/RootLayout/Footer/FooterSelector";
import { headers } from "next/headers";
import GoogleLogger from "@/components/GoogleLogger";
import { Toaster } from "sonner";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, getLocale } from "next-intl/server";
import { WishlistProvider } from "@/context/WishlistContext";
import { CurrencyProvider } from "@/context/CurrencyContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const pathname = headersList.get("x-pathname") || "";
  const isAdmin = pathname.startsWith("/admin");
  const isAuthPage = /\/(signin|register|forgot-password|reset-password)(\/|$)/.test(pathname);

  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
        suppressHydrationWarning
      >
        <NextIntlClientProvider messages={messages}>
          <CurrencyProvider>
          <WishlistProvider>
            <GoogleLogger />
            {!isAdmin && !isAuthPage && <HeaderSelector />}
            {children}
            {!isAdmin && !isAuthPage && <FooterSelector />}
            <Toaster position="top-right" richColors />
          </WishlistProvider>
          </CurrencyProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
